name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest-xlarge

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          brew install tuist &&
          tuist generate &&
          ruby ci_scripts/test.rb --device "iPhone 14" --version 16.4 --scheme StripeiOS | xcpretty
